---
deployment:
  tasks:
    - export DEPLOYPATH=/home/icsorg/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp advisors.html $DEPLOYPATH
    - /bin/cp organisers.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
