---
deployment:
  tasks:
    - export DEPLOYPATH=/home/icsorg/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp advisors.html $DEPLOYPATH
    - /bin/cp organisers.html $DEPLOYPATH
    - /bin/cp about-kkr.html $DEPLOYPATH
    - /bin/cp about-nit-kkr.html $DEPLOYPATH
    - /bin/cp about-dept.html $DEPLOYPATH
    - /bin/cp publication.html $DEPLOYPATH
    - /bin/cp papers.html $DEPLOYPATH
    - /bin/cp submissions.html $DEPLOYPATH
    - /bin/cp tracks.html $DEPLOYPATH
    - /bin/cp dates.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
